### ISSUE TITLE
Option to avoid outputting to a subdirectory

### ISSUE THREAD

**Issue by alecthomas** [go101/golds#14] opened 2021-03-23 23:34 UTC
Or preferably, just don't output to a subdirectory at all - the user already controls the flag, so they can specify whatever directory they prefer.

When I use `-dir=docs` I expect that the docs will actually be in _that_ directory, not a subdirectory. This is unintuitive as-is, but also causes actual problems when trying to deploy docs through CI because the general expectation is that the CI pipeline can point to a static directory and just push it up to the documentation site. As the sub-directory changes on each invocation, this expectation is broken.

**Comment by go101** [comment] 2021-03-24 14:56
Good advice, though there is a small incompatibility problem caused by this behavior change, I think the change is worthy to make.

The behavior will not change if the `-dir` option is not presented.

**Comment by go101** [comment] 2021-04-17 18:24
This should be fixed in tip.

**Comment by alecthomas** [comment] 2021-04-17 21:55
Brilliant thanks, I'll give it a shot this week.

**Comment by alecthomas** [comment] 2021-04-17 22:54
This works perfectly, thanks!

**Comment by go101** [comment] 2021-04-18 14:20
OK. I will close this issue.

**Closed by go101** 2021-04-18 14:20 UTC
